// Generated by `drizzle-kit pull` against Supabase (schema: housewarming),
// then renamed exports for ergonomics. Re-run `npm run db:pull` after schema
// changes and apply the same renames.
import { sql } from "drizzle-orm";
import {
  check,
  foreignKey,
  index,
  integer,
  pgSchema,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

export const housewarming = pgSchema("housewarming");

export const gifts = housewarming.table(
  "gifts",
  {
    id: text().primaryKey().notNull(),
    titlePl: text("title_pl").notNull(),
    titleUk: text("title_uk").notNull(),
    descPl: text("desc_pl").notNull(),
    descUk: text("desc_uk").notNull(),
    price: text().notNull(),
    quantity: integer(),
    sortOrder: integer("sort_order").default(0).notNull(),
    shopUrl: text("shop_url"),
  },
  () => [
    check("gifts_quantity_check", sql`(quantity IS NULL) OR (quantity >= 1)`),
  ],
);

export const reservations = housewarming.table(
  "reservations",
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    giftId: text("gift_id").notNull(),
    claimer: text().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "string" })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("reservations_claimer_idx").using(
      "btree",
      table.claimer.asc().nullsLast().op("text_ops"),
    ),
    index("reservations_gift_idx").using(
      "btree",
      table.giftId.asc().nullsLast().op("text_ops"),
    ),
    foreignKey({
      columns: [table.giftId],
      foreignColumns: [gifts.id],
      name: "reservations_gift_id_fkey",
    }).onDelete("cascade"),
    unique("reservations_gift_id_claimer_key").on(table.giftId, table.claimer),
  ],
);
