-- Seed wish-list gifts. Images live under /public/housewarming/wishlist/<id>.<ext>.
-- Each row's `id` is a UUID; the matching image file shares that UUID as filename.
-- Rows are sorted by approximate PLN price; sort_order is stepped by 10 so new
-- items can be inserted between existing ones without renumbering.

INSERT INTO housewarming.gifts (id, title_pl, title_uk, desc_pl, desc_uk, price, quantity, sort_order, shop_url, alt_price, alt_shop_url) VALUES
  (
    '9baef3dc-536f-4f9b-a4af-57966d5b13ce',
    'Stojak na szczoteczkę MUJI',
    'Підставка для зубної щітки MUJI',
    'Porcelanowy stojak na szczoteczkę do zębów w żółtym kolorze.',
    'Порцелянова підставка для зубної щітки жовтого кольору.',
    '~ 25 zł',
    2,
    100,
    'https://muji.com.pl/higiena-jamy-ustnej/1006568-stojak-na-szczoteczke-do-zebow-porcelanowy-zolty.html',
    NULL,
    NULL
  ),
  (
    '76141216-f5d9-48cc-a2ec-dd796eb4adac',
    'Wieszak ścienny terrazzo',
    'Настінна вішалка terrazzo',
    'Ręcznie robiony wieszak ścienny.',
    'Ручної роботи настінна вішалка.',
    '~ 40 zł',
    4,
    110,
    'https://www.etsy.com/pl/listing/4375241285/rcznie-robiony-wieszak-cienny-terrazzo-o',
    NULL,
    NULL
  ),
  (
    '46058ee4-2bdc-4ae9-b821-1789f96c8634',
    'Miska Tumbled',
    'Миска Tumbled',
    'Miska ze stali nierdzewnej.',
    'Миска з нержавіючої сталі.',
    '~ €15',
    1,
    120,
    'https://fermliving.com/products/tumbled-bowl-stainless-steel',
    NULL,
    NULL
  ),
  (
    'c1ed7dbf-a69b-42e3-9d38-d1cba74141c0',
    'Aqara P100',
    'Aqara P100',
    'Czujnik stanu obiektu - Aqara P100.',
    'Датчик стану об''єкта — Aqara P100.',
    '~ 120 zł',
    4,
    130,
    'https://www.euro.com.pl/czujniki/aqara-p100-bialy.bhtml',
    NULL,
    NULL
  ),
  (
    '3904a20e-93f5-4a73-8ff4-126f43ac9390',
    'SKATGÅS',
    'SKATGÅS',
    'LED lampki tealight z płytką do ładowania.',
    'LED-чайні свічки із зарядною підставкою.',
    '~ 130 zł',
    1,
    135,
    'https://www.ikea.com/pl/pl/p/skatgas-zestaw-tealightow-led-z-plytka-do-ladowania-bialy-80611596/',
    '~ 50 zł',
    'https://www.ikea.com/pl/pl/p/skatgas-zestaw-tealightow-led-z-plytka-do-ladowania-bialy-00611595/'
  ),
  (
    '2f8a9b93-735e-4820-91a8-0a8a9ea39883',
    'Bain Marie Pot',
    'Bain Marie Pot',
    'Bain Marie Pot (Dla mnie tam wygląda jak garnek ~ Emil)',
    'Bain Marie Pot (Як на мене, то виглядає як каструля ~ Emil)',
    '~ 130 zł',
    1,
    140,
    'https://www.amazon.com/dp/B0DK81PT7P',
    NULL,
    NULL
  ),
  (
    '12ee535b-a910-49d1-b621-a6205587d28f',
    'Łyżki Kunz',
    'Ложки Kunz',
    'Łyżki ze stali nierdzewnej – Chef Kunz.',
    'Ложки з нержавіючої сталі – Chef Kunz.',
    '~ 140 zł',
    1,
    150,
    'https://www.amazon.pl/dp/B0FCS7PXXJ',
    NULL,
    NULL
  ),
  (
    '9914d056-8584-4478-bf91-3a0c5884dbb1',
    'Aqara FP300',
    'Aqara FP300',
    'Czujnik obecności, światła, temperatury i wilgotności.',
    'Датчик присутності, освітлення, температури та вологості.',
    '~ 190 zł',
    6,
    160,
    'https://www.empik.com/aqara-presence-sensor-fp300-czujnik-obecnosci-zigbee-matter-aqara,p1702113971,dom-i-ogrod-p',
    NULL,
    NULL
  ),
  (
    '96ac497b-d97c-4789-a8f6-eed490aec348',
    'Zestaw Essentielle Maison Berger',
    'Набір Essentielle Maison Berger',
    'Minimalistyczna lampa zapachowa w kształcie kuli z dwoma esencjami.',
    'Мінімалістична ароматична лампа у формі кулі з двома есенціями.',
    '~ 200 zł',
    1,
    170,
    'https://maisonbergerparis.com.pl/293-zestaw-essentielle-okragly.html',
    NULL,
    NULL
  ),
  (
    'd6844dae-2584-449c-acd3-f7b3b507cf2c',
    'Talerze deserowe Aegean',
    'Десертні тарілки Aegean',
    'Zestaw czterech talerzy deserowych.',
    'Набір з чотирьох десертних тарілок.',
    '~ $60',
    1,
    180,
    'https://fiestafactorydirect.com/products/aegean-classic-rim-7-1-4-inch-salad-plate-set-of-4',
    NULL,
    NULL
  ),
  (
    '668cb8e9-2678-4ca2-afff-1119bb190c6c',
    'Młynek Cherry Chubbie',
    'Млинок Cherry Chubbie',
    'Młynek do soli lub pieprzu z drewna kauczukowego w wiśniowym lakierze.',
    'Млинок для солі або перцю з каучукового дерева у вишневому лаку.',
    '~ €60',
    1,
    190,
    'https://eu.addisonross.com/en-eu/products/cherry-chubbie-salt-or-pepper-mill-grinder',
    NULL,
    NULL
  ),
  (
    '62357bbc-1196-4684-82dc-4a5acae42477',
    'Młynek Sage Chubbie',
    'Млинок Sage Chubbie',
    'Młynek do soli lub pieprzu z drewna kauczukowego w szałwiowym lakierze.',
    'Млинок для солі або перцю з каучукового дерева в шавлієвому лаку.',
    '~ €60',
    1,
    200,
    'https://eu.addisonross.com/en-eu/products/sage-chubbie-salt-or-pepper-mill-grinder',
    NULL,
    NULL
  ),
  (
    '9e514276-7926-4b0a-baec-317c0c7de1e4',
    'Stojak na książki Penguin x MOEBE',
    'Підставка для книг Penguin x MOEBE',
    'Minimalistyczny stojak na książki w pomarańczowym kolorze (na 90. rocznicę wydawnictwa Penguin Books).',
    'Мінімалістична підставка для книг помаранчевого кольору (до 90-ї річниці видавництва Penguin Books).',
    '~ €60',
    1,
    210,
    'https://moebe.dk/products/penguin-x-moebe-book-stand',
    NULL,
    NULL
  ),
  (
    '5f6194a9-bf1d-42f8-88e4-d88ec0f34c0e',
    'Gasidło do świec Landscape',
    'Гасник для свічок Landscape',
    'Porcelanowe gasidło do świecy.',
    'Порцеляновий гасник для свічки.',
    '~ 270 zł',
    1,
    220,
    'https://emea.diptyqueparis.com/en-pl/products/landscape-snuffer-deco01282',
    '~ 170 zł',
    'https://emea.diptyqueparis.com/en-pl/products/gold-snuffer-for-candles'
  ),
  (
    '33db6965-825c-4e1e-85f3-bbc9a8dabb6f',
    'Mydło do rąk Softening',
    'Рідке мило для рук Softening',
    'Mydło do rąk z lawendą, rozmarynem, ylang-ylang i bursztynem.',
    'Мило для рук з лавандою, розмарином, іланг-ілангом та бурштином.',
    '~ 300 zł',
    1,
    230,
    'https://emea.diptyqueparis.com/en-pl/products/softening-hand-wash-glass-1-handsoapg1',
    NULL,
    NULL
  ),
  (
    '53e72d60-99a3-4900-94e6-d4fa2160d4bb',
    'Talerz Kapibary',
    'Тарілка Капібари',
    'Talerz Kapibary, wymaga indywidualnego zamówienia poprzez kontakt z autorką (btw, wykonywany na Ząbkowskiej).',
    'Тарілка Капібари, потребує індивідуального замовлення через контакт з авторкою (btw, виготовляється на Ząbkowskiej).',
    '~ 300 zł',
    1,
    240,
    'https://lekka-store.pl/produkt/talerz-kapibary-20-cm-kopia/',
    NULL,
    NULL
  ),
  (
    'c9d91a34-2d64-427e-9475-bb96dcd93395',
    'Deska do krojenia Tramontina',
    'Дошка для нарізки Tramontina',
    'Deska do krojenia.',
    'Дошка для нарізки.',
    '~ 330 zł',
    1,
    250,
    'https://www.knivesandtools.pl/pl/pt/-deska-do-krojenia-tramontina-landhaus-13998-050-drewno-tekowe-45-x-34-cm.htm',
    '~ 240 zł',
    'https://baywood.store/en/products/deska-orzechowa-sztorcowa-duza-l'
  ),
  (
    'a3dd14af-7189-42e5-b83a-55b18718f5b7',
    'HOTO AutoCare',
    'HOTO AutoCare',
    'Poręczny, bezprzewodowy odkurzacz, pompka i dmuchawa.',
    'Зручний бездротовий пилосос, насос і повітродувка.',
    '~ 370 zł',
    1,
    260,
    'https://hototools.com/products/hoto-autocare-air-duster-vacuum',
    NULL,
    NULL
  ),
  (
    '74a63aa6-8105-4432-a90b-4bdb3494804e',
    'Wok Yosukata',
    'Вок Yosukata',
    'Patelnia wok ze stali węglowej.',
    'Сковорода-вок з вуглецевої сталі.',
    '~ 400 zł',
    1,
    270,
    'https://www.amazon.pl/dp/B07VJ5LGJ9',
    NULL,
    NULL
  ),
  (
    'beece97d-66d5-42d8-b620-3fdf1bfaba54',
    'Świeca Ambre',
    'Свічка Ambre',
    'Klasyczna świeczka zapachowa Diptyque.',
    'Класична ароматична свічка Diptyque.',
    '~ 440 zł',
    1,
    280,
    'https://emea.diptyqueparis.com/en-pl/products/candle-ambre-300g',
    '~ 300 zł',
    'https://emea.diptyqueparis.com/en-pl/products/ambre-classic-candle'
  );
